### ISSUE TITLE
using image

### ISSUE THREAD

**Issue by pgte** [ljwagerfield/crdt#1]
Hi Lawrence,

Protocol Labs (author of IPFS) are building a open-source free collaborative decentralised text editor named Peerpad and we're using CRDTs. I recently saw this explanation of CRDTs, which is great and, we've added it to the list of resources (see https://github.com/ipfs/research-CRDT/pull/10).

We're building a very succinct explanation of CRDTs for the homepage of Peerpad that we're building and we'd like to create an illustration based on [your image](https://github.com/ljwagerfield/crdt/blob/master/images/monotonic-join-semilattice.gif), which I think illustrates well CRDTs, if you give us permission to. (I was looking at the repo and was not sure of the usage license). Could you please clarify?

Thanks so much!

**Comment by ljwagerfield** [comment]
Hi Pedro,

Please feel free to distribute and derive to your heart's content!

Thank you for the note,
Lawrence

**Comment by pgte** [comment]
Thank you Lawrence!
